packages:
  - apps/*
  - packages/*

catalog:
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  react: 19.2.3
  react-dom: 19.2.3
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
