packages:
  - packages/*

catalog:
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  react: 19.2.0
  react-dom: 19.2.0

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
