packages:
  - packages/*

catalog:
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  react: 19.2.0
  react-dom: 19.2.0
  tailwindcss: 4.1.15
  tailwind-merge: 3.3.1

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
