packages:
  - apps/*
  - packages/*

catalog:
  '@storybook/addon-a11y': 10.1.9
  '@storybook/addon-docs': 10.1.9
  '@storybook/addon-vitest': 10.1.9
  '@storybook/nextjs-vite': 10.1.9
  '@storybook/react-vite': 10.1.9
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@types/node': 24.10.3
  '@vitest/browser-playwright': 4.0.16
  '@vitest/coverage-v8': 4.0.16
  '@vitest/ui': 4.0.16
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  playwright: 1.57.0
  react: 19.2.3
  react-dom: 19.2.3
  storybook: 10.1.9
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  vitest: 4.0.16
  vitest-browser-react: 2.0.2

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
